# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            "Mohabat Tarkeshian"
tagline:          ""
description:      "mathematics and life"
url:              https://mohabatt.github.io
baseurl:          /

author:
  name:           Mohabat Tarkeshian
  url:            https://mohabatt.github.io

plugins:
  - jekyll-paginate
  - jekyll-feed

# Sets blog page to have previews
paginate:         5
paginate_path: "blog/page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mohabatt/mohabatt.github.io

exclude:
  - Gemfile
  - Gemfile.lock

# Social media usernames
github_username:   mohabatt
twitter_username:  mohabattt
